version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  # - package-ecosystem: "bundler"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "composer"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "devcontainers"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "mix"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "elm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  # - package-ecosystem: "maven"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "nuget"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "pub"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "swift"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "terraform"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50

  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 50
