site_name: pc-com-bot development document
site_author: パソコンコミュニティ
copyright: 'Copyright (c) 2024 パソコンコミュニティ.'
use_directory_urls: false

theme:
  name: material

plugins:
  search:
    lang: ja
  awesome-pages:
    order_by: filename
  offline:

theme:
  name: material
  locale: ja
  language: ja
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.path
    - header.autohide
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight


extra:
  homepage: https://pc-com.github.io/pc-com-bot
  search:
    language: ja
  generator: false

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.tilde
  - footnotes
  - admonition
  #- plantuml_markdown:
  #    server: https://
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: false


