name: build

on:
  push:
    branches: 
      - master
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore: 
      - 'docs/**' 
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: build
        run: chmod +x ./gradlew && ./gradlew check test build
