name: Wiki Update

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: docs
          path: main

      - name: Checkout Wiki Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}.wiki"
          path: wiki

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email $(git -C main log --no-merges --pretty='%ae' -n1 HEAD)

      - name: Update Wiki
        run: |
          rsync -a --delete main/docs/ wiki/
          cd wiki
          git add .
          git commit -m "${GITHUB_WORKFLOW}"
          git push
